### PR TITLE
Password reset uri

### PR DESCRIPTION
**Pull request by Craig-IAS**
Link in reset email was taking you to the change password dashboard that required your old password.

### CODE REVIEW

**Comment by Craig-IAS** [comment]
Done

> @Craig-IAS you have included 2 unrelated commits. Please fix.

Done

**Comment by jazdw** [comment]
@Craig-IAS in the future, please either a) squash your changes and force push b) rebase interactive and force push

**Comment by jazdw** [comment]
I'm not going to merge this as it is a mess.

**Comment by jazdw** [comment]
Fixed via 36e155de01c992fcc0d8b786dde1f720cdf1f569

**Pull request closed without merging**
