### PR TITLE
event-handler-fixes

### PR DESCRIPTION
**Pull request by guetteluis**

### CODE REVIEW

**Comment by jazdw** [comment]
Why did you remove the min/max validation? We still want that, its just the `ma-tr-args` attribute was wrong. It should be an array not a string.

**Comment by jazdw** [comment]
Also you should use the `ng-attr-min` attribute instead of `min` if it contains an interpolation expression.

**Comment by luisguette** [comment]
@Puckfist wrote this in asana: 

Not quite. The min and the max are only properties of certain virtual numeric points. And, they are not constraints on valid values to set. I would consider it okay for the moment to just remove validating the number beyond its being a number.

But, there is a mechanism in Mango that could be appropriate to use. There should be a boolean at targetPoint.preventSetExtremeValues which if true would lead the validation to use targetPoint.setExtremeLowLimit as the minimum and targetPoint.setExtremeHighLimit

**Comment by luisguette** [comment]
That's why I removed the validations

**Comment by guetteluis** [comment]
@Puckfist wrote this in asana:

Not quite. The min and the max are only properties of certain virtual numeric points. And, they are not constraints on valid values to set. I would consider it okay for the moment to just remove validating the number beyond its being a number.

But, there is a mechanism in Mango that could be appropriate to use. There should be a boolean at targetPoint.preventSetExtremeValues which if true would lead the validation to use targetPoint.setExtremeLowLimit as the minimum and targetPoint.setExtremeHighLimit

**Comment by guetteluis** [comment]
that's why I removed the validations

**Comment by jazdw** [comment]
@guetteluis OK, I wasn't aware of that. That would be something helpful to include in the description.

**Pull request merged**
