### PR TITLE
Admin home restructure

### PR DESCRIPTION
**Pull request by pierpuccini**
Restructured admin home for mango v4

### CODE REVIEW

**Comment by terrypacker** [comment]
@jazdw can we merge this?  There is a backend issue with the units on the disk space and things we will likely want to tweak but in general it is ready.

**Comment by jazdw** [comment]
@pierpuccini Terry wants to get this merged in pretty soon. Some things that I need fixed first are -
* Remove the changes to package.json and yarn.lock
* CSS classes without a prefix e.g. `.big`
* Hardcoded colors in the CSS
* Id references in the CSS, use classes in instead e.g. #ma-ui-home-page-watermark
* Remove `id` attributes from the markup

Other things which may need to be changed are
* CSS grid layout - not used anywhere else in our codebase, could cause issues, need cross browser testing. If possible change to flex layout
* There seems to be a lot of CSS in general, see if you can condense this down into some utility classes which you can apply to multiple elements. The more CSS we have the harder it is to update and maintain down the track

**Comment by jazdw** [comment]
Contrast needs to be fixed, please ensure you are using colors from the material palette and testing with the default light and dark themes -

image

image

This should also have a thicker line around it -
image

**Comment by jazdw** [comment]
The code is much better now, way less CSS, thanks for that. I think we still need to work on making it match the design better though. I will play around with it a bit.

Few things -
- Utilities view all button goes to log files for some reason
- Reports view all button does nothing
- Events view all button does nothing
- White border on hover should be around outside of whole box 
image
- Graph is clipped 
image

**Comment by jazdw** [comment]
Current appearance after changes I made -
image

**Pull request merged**
