### PR TITLE
Serial port select component

### PR DESCRIPTION
**Pull request by guetteluis**
- You can select one or multiple serial ports.
- You can show/hide Icon
- You can customize label
- You can add clear option

### CODE REVIEW

**Comment by jazdw** [comment]
@guetteluis Just realized that @terrypacker said something about passing a refresh parameter to the REST API. We might need a boolean attribute on this component that controls if it should refresh the list of serial ports when getting the list. Terry can you give direction on when this needs to be done?

Luis, just create a new PR when complete. Thanks.

**Comment by terrypacker** [comment]
@guetteluis the refresh parameter should be used by a button/icon on the widget.  In the legacy UI the initial load of the list is done without a refresh but there is a button next to the drop down that lets you reload the list via a refresh.

Refreshing the list can take some time so we only want to do it when the user clicks this button/icon.

The workflow should be:

1. On page load/widget open or display make a GET request with refresh=false this will load the cached list of ports
2. If the user does not see the port they want they can click the button/icon to refresh and at this point you make a GET request with refresh=true

**Comment by luisguette** [comment]
ok, working on that

**Comment by guetteluis** [comment]
ok, working on that

**Comment by jazdw** [comment]
Fixed via #215

**Pull request merged**
